### ISSUE TITLE
Autodj is taking over the live broadcast 

### ISSUE THREAD

**Issue by Mirel81** [AzuraCast/azuracast.com#97]
When a dj connects , works fine , then autodj  interrupts the live broadcast every 2 minutes for a few seconds after it resumes to the live broadcast.

**Comment by BusterNeece** [comment]
Most of the time, what folks are hearing as the AutoDJ "interrupting" a live broadcast is actually the live broadcast signal not being stable and the AutoDJ just falling back to its regular programming because it thinks the DJ has disconnected.

On the "Broadcasting" tab of your station's profile, you can increase the buffer for DJs until this issue doesn't happen as often. What buffer works well for you will depend on your installation and many other factors.

**Comment by Mirel81** [comment]
Thanks for your resonse , i increased the buffer  in broadcast tab from 5 to 35 , but the result to this is that it does not do it so often , so now instead of interrupting every 2 minutes , the interuptions are every 12 min , but the problem is still there.About signal consistency i would say that is not the problem since the sound comes from a broadcast processor , which has the signal stable  at the same volume all the time. Is there any other way to instruct liquidsoap not to do this?Below is the log.
![log](https://github.com/AzuraCast/azuracast.com/assets/158329196/02f44c0c-47c2-4b06-8ded-a247abe65f0d)

**Comment by Mirel81** [comment]
Right i figured out why autodj  was interupting live dj , it has to do with the  actual clocks, physical server is in utc+1 , the azuracst configuration on the broadcasting side was set to utc+2 , and i was streaming from utc 0, aparently this made the liquidsoap not to be able to unify clocks.So , after i set the azuracast server to the same clock as the physical server  on utc+1 , the problem  was solved .Also , when you are live streaming you are sending  your actual local computer clock to liquidsoap , one way to trick liquidsoap, not to be confused about the clocks is to set your own computer clock  to  match the actual server clock if you are on a different timezone. I can confirm this was tested , and works.
